### ISSUE TITLE
@-lines actually processed?

### ISSUE THREAD

**Issue by infabo** [b13/bolt#2]
Hi,

are lines starting with one of these @-command really processed?

```
@isroot
@clear
@sitetitle "My site title only in constants available"
```

see https://github.com/CMSExperts/bolt/blob/master/Configuration/TypoScript/setup.typoscript

**Comment by bmack** [comment]
hey,

not done unfortunately. this would be really cool to have, however that'd be breaking and we'd need to have proper tests on that.

**Comment by lolli42** [comment]
Hey.

I'm unsure if we still need this: Since this was only mentioned in the example file and never working, I removed mentions of these @ things for now with https://github.com/b13/bolt/pull/25/files#diff-b283fa76060bccbae79c0465294ef56f7ebf57b8e70dab356a1d7c48d7f00ee9

With v12, the Template Analyzer now shows the include properly and a decent title is set. We could discuss about @clear and @isroot, but maybe this is kinda obsolete since the new event listener usage in v12 tries to set root and clear flags in useful way by default, and in (really very rare?!) situations where these don't fit, a second listener could change the rows again if really needed.

Since these things haven't ever been implemented anyways, I'd tend to close with 'won't have'?

**Comment by infabo** [comment]
I would be fine with closing this issue.
