### ISSUE TITLE
Ability to customise prefix

### ISSUE THREAD

**Issue by mikestreety** [b13/bolt#40]
This looks like such a useful extension and would love to consider using it.

Would you consider allowing the ability to customise the `site_` prefix? 

I understand why your conventions enforce that, but for plugging this into an existing site, it would be great if this could be customised (or, in my case, removed).

Thanks

**Comment by bmack** [comment]
AFAICR you only set this with the site settings and can choose any extension key like this (from the README) since a few TYPO3 versions (v10+):

"Either manually edit the Site Configuration .yaml file and add sitePackage: '<my_extension_key>' as top-level key, or edit the Site Configuration in the Backend "Sites" module, select the site package / extension in the drop and save it."

**Comment by mikestreety** [comment]
Oh perfect, i'll give it a go setting it manually, thanks :) 

I think, when I read that, I thought there was more magic for `site_` stuff, but looking through the code it's just on the select drop down 👍
